### ISSUE TITLE
Add Playground setting properties through .yml or .properties

### ISSUE THREAD

**Issue by AnneMayor** [leangen/graphql-spqr#503]
Hi,

I am using this library to our project. It really helps a lot.
However, I would like to suggest one feature that would be more helpful.
For now, I am using Playground to provide clients(mobile, frontend) with query and parameter docs and sample test like swagger.
I found out that the default setting is `schema.polling.enable = true`. This leads to create many unnecessary server logs. Could you please add new setting properties like [graphql-playground](https://mvnrepository.com/artifact/com.graphql-java-kickstart/playground-spring-boot-starter) library?

```
spring:
  playground:
    enabled: true
    settings:
      schema:
        polling:
          enable: false
```

**Comment by AnneMayor** [comment]
I found out one solution and it works well.
Therefore, I closed this issue.
```
graphql:
  spqr:
    playground:
      settings:
        schema:
          polling:
            enable: false
```
