### ISSUE TITLE
SPQR gui settings in .properties/.yml does not work

### ISSUE THREAD

**Issue by AnneMayor** [leangen/graphql-spqr#504]
Hi,

I am using spqr gui and customizing some settings(endpoint, target-endpoint, page-title).
However, a page-title setting does not work well as I expected.(endpoint and target-end point settings work well like the below)
Here is a code that I wrote.
```yml
graphql:
  spqr:
    gui:
      enabled: true
      endpoint: /sample
      target-endpoint: /sample
      page-title: Let's play GraphQL!
```

result:
<img width="1507" alt="스크린샷 2024-07-21 오후 5 06 46" src="https://github.com/user-attachments/assets/d40587f8-5026-4fd3-aa87-9a54c4c07200">
<img width="377" alt="스크린샷 2024-07-21 오후 5 07 04" src="https://github.com/user-attachments/assets/7cae7388-1139-46e8-9cb1-ab0c521b2b2f">

Please, let me know if there is something that I have to more.
